### ISSUE TITLE
Building provided examples

### ISSUE THREAD

**Issue by elfring** [mmottl/pcre-ocaml#8]
[A build specification](https://github.com/mmottl/pcre-ocaml/blob/258b72cf6ec67362a137ebc434a5a52fd2610077/_oasis#L38 "Building examples for PCRE-OCaml") mentions four examples for your software library.
I wonder that the generated make file does not contain corresponding build targets so far.

Will it become easier to try a program like “[pcregrep](https://github.com/mmottl/pcre-ocaml/blob/725120d182d39e4e9e8e21e74e2cbae8ca293db7/examples/pcregrep/pcregrep.ml "Grep with PCRE-OCaml")” out?

**Comment by mmottl** [comment]
The examples weren't really intended for everyday use but to teach people how to use the API.  They are not installed.  Building them may help expose compilation and linking problems with the library, which is why they are built by default.  You can always copy them from the source distribution to toy with them.

**Comment by elfring** [comment]
Would it make sense to convert any of your examples to [a better supported test case](https://en.wikipedia.org/wiki/Test_case "Development for test cases?") for the software build system?

**Comment by mmottl** [comment]
The primary goal of the examples was for developers to learn how to use the API.  It would be nice to have a dedicated test suite for every library, including for build errors, but the above solution was sufficient so far.

**Comment by elfring** [comment]
* Would you like to distinguish more between examples and test cases for better software demonstration?
* Does [the build system](http://oasis.forge.ocamlcore.org/ "Checking the capabilities of OASIS") need any related improvements?

**Comment by mmottl** [comment]
The examples are in no way a proper test suite.  They don't actually verify that the library works correctly, but building them by default makes sure that at least some compilation or linking errors are detected early.  I don't see an imminent need for introducing test suites right now, since there are no known bugs in the library and no major changes in the near future.

**Comment by elfring** [comment]
I would appreciate when I can check directly if a bigger regular expression will also work together with the provided OCaml programming interface.

**Comment by mmottl** [comment]
Please submit a pull request if you would like to contribute features you need.
